Consulting/Models/Lendet.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Consulting.Models
{
    public class Lendet
    {
        [Key]
        public int Lid { get; set; }
        [Required]
        [DisplayName("Emri i lendes")]
        [MaxLength(40)]
        public string? Lname { get; set; }
        [Required]
        [DisplayName("Pershkrimi")]
        public string? Ldescription { get; set; }
    }
}

Consulting/Areas/Admin/Controllers/LendetController.cs
using Consult.DataAcess.Data;
using Consult.Models;
using Consult.Models.ViewModels;
using Consult.Utility;
using Cunsult.DataAcess.Repository;
using Cunsult.DataAcess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Consulting.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class LendetController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public LendetController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Lendet> LendetList = _unitOfWork.Lendet.GetAll().ToList();
            return View(LendetList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            LendetVM obj = new LendetVM();

            obj.DepartamentList = _unitOfWork.Departamentet.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString(),
            });

            obj.VitiList = _unitOfWork.Viti.GetAll().Select(u => new SelectListItem
            {
                Text = u.VitiName,
                Value = u.Vid.ToString(),
            });

            return View(obj);
        }

        [HttpPost]
        public IActionResult Create(LendetVM obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Lendet.Add(obj.Lendet);
                _unitOfWork.Save();

                TempData["success"] = "Lenda eshte krijuar me sukses";
                return RedirectToAction("Index");
            }

            // Only populate these lists if ModelState is not valid.
            //obj.DepartamentList = _unitOfWork.Departamentet.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.Name,
            //    Value = u.Id.ToString(),
            //});

            //obj.VitiList = _unitOfWork.Viti.GetAll().Select(u => new SelectListItem
            //{
            //    Text = u.VitiName,
            //    Value = u.Vid.ToString(),
            //});

            return View(obj);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _unitOfWork.Lendet.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null)
            {
                return NotFound();
            }
            return View(lendetprejdb);
        }
        [HttpPost]
        public IActionResult Edit(Lendet obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Lendet.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Lenda eshte edituar me sukses";
                return RedirectToAction("Index");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _unitOfWork.Lendet.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null)
            {
                return NotFound();
            }
            return View(lendetprejdb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Lendet? obj = _unitOfWork.Lendet.Get(u => u.Lid == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Lendet.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Lenda eshte fshire me sukses";
            return RedirectToAction("Index");
        }
    }
}

Consulting/Controllers/LendetController.cs
using Consult.DataAcess.Data;
using Consult.Models;
using Cunsult.DataAcess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace Consult.Controllers
{
    public class LendetController : Controller
    {
        private readonly ILendetRepository _lendetrep;
        public LendetController(ILendetRepository db)
        {
            _lendetrep = db;
        }
        public IActionResult Index()
        {
            List<Lendet> LendetList = _lendetrep.GetAll().ToList();
            return View(LendetList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Lendet obj)
        {
            //if (obj.Lname == obj.Ldescription.ToString())
            //{
            //    ModelState.AddModelError("Emri", "Emri i lendes dhe pershkrimi nuk mund te jene te njejta");
            //}
            if (ModelState.IsValid)
            {
                _lendetrep.Add(obj);
                _lendetrep.Save();
                TempData["success"] = "Lenda eshte krijuar me sukses";
                return RedirectToAction("Index");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _lendetrep.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null) 
            {
                return NotFound(); 
            }
            return View(lendetprejdb);
        }
        [HttpPost]
        public IActionResult Edit(Lendet obj)
        {

            if (ModelState.IsValid)
            {
                _lendetrep.Update(obj);
                _lendetrep.Save();
                TempData["success"] = "Lenda eshte edituar me sukses";
                return RedirectToAction("Index");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _lendetrep.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null)
            {
                return NotFound();
            }
            return View(lendetprejdb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Lendet? obj = _lendetrep.Get(u => u.Lid == id);
            if (obj == null)
            {
                return NotFound();
            }
            _lendetrep.Remove(obj);
            _lendetrep.Save();
            TempData["success"] = "Lenda eshte fshire me sukses";
            return RedirectToAction("Index");
        }
    }
}

Consulting/Areas/Admin/Views/Lendet/Create.cshtml
@model Consult.Models.ViewModels.LendetVM;

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Krijo Lende
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row" >
            <div class="border p-3">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Lendet.Lname" class="form-control border-0 shadow"/>
                    <label asp-for="Lendet.Lname" class="ms-2"></label>
                    <span asp-validation-for="Lendet.Lname" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <select asp-for="Lendet.DepartamentId" asp-items="@Model.DepartamentList" class="form-select border-0 shadow">
                        <option disabled selected>
                            --Selekto Departamentin --
                        </option>
                    </select>
                    <label asp-for="Lendet.DepartamentId" class="ms-2"></label>
                    <span asp-validation-for="Lendet.DepartamentId" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <select asp-for="Lendet.VitiID" asp-items="@Model.VitiList" class="form-select border-0 shadow">
                        <option disabled selected>
                            --Selekto Vitin --
                        </option>
                    </select>
                    <label asp-for="Lendet.VitiID" class="ms-2"></label>
                    <span asp-validation-for="Lendet.VitiID" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Krijo</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Lendet" asp-action="Index" class="btn btn-outline-primary border form-control">
                            Kthehu ne list
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

Consulting/Areas/Admin/Views/Lendet/Delete.cshtml
<h1>Delete</h1>
@model Lendet

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Fshi Lende
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Lid" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Lname" disabled type="text" class="form-control border-0 shadow" />
                    <label asp-for="Lname" class="ms-2"></label>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-danger form-control">Delete</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Lendet" asp-action="Index" class="btn btn-outline-secondary border form-control">
                            Kthehu ne list
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

Consulting/Areas/Admin/Views/Lendet/Edit.cshtml
<h1>Edit</h1>
@model Lendet
<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Edito Lende
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post">
            <input asp-for="Lid" hidden />
            <div class="border p-3 mt-4">
                <div class="form-floating py-2 col-12">
                    <input asp-for="Lname" type="text" class="form-control border-0 shadow" />
                    <label asp-for="Lname" class="ms-2"></label>
                    <span asp-validation-for="Lname" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="DepartamentId" class="form-control border-0 shadow" />
                    <label asp-for="DepartamentId" class="ms-2"></label>
                    <span asp-validation-for="DepartamentId" class="text-danger"></span>
                </div>
                <div class="form-floating py-2 col-12">
                    <input asp-for="VitiID" class="form-control border-0 shadow" />
                    <label asp-for="VitiID" class="ms-2"></label>
                    <span asp-validation-for="VitiID" class="text-danger"></span>
                </div>
                <div class="row mt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Lendet" asp-action="Index" class="btn btn-outline-secondary border form-control">
                            Kthehu ne list
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Consulting/Areas/Admin/Views/Lendet/Index.cshtml
@model List<Lendet>
@if (TempData["success"] != null)
{
        <h2>@TempData["success"]</h2>
}

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary m-lg-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">
                    Lista e Lendeve
                </h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Lendet" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle-fill"></i> Krijo nje lende
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Emri i Lëndës
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Lname</td>
                        <td>
                            <div class="w-75 btn btn-group" role="group">
                                <a asp-controller="Lendet" asp-action="Edit" asp-route-id="@obj.Lid" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Lendet" asp-action="Delete" asp-route-id="@obj.Lid" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>