Consulting/Areas/Admin/Controllers/DepartamentetController.cs
using Consult.DataAcess.Data;
using Consult.Models;
using Consult.Models.ViewModels;
using Consult.Utility;
using Cunsult.DataAcess.Repository;
using Cunsult.DataAcess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Data;

namespace Consulting.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class DepartamentetController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DepartamentetController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Departament> DepartamentetList = _unitOfWork.Departamentet.GetAll().ToList();
            return View(DepartamentetList);
        }

        public IActionResult Upsert(int? id)
        {
            if (id == null || id == 0)
            {
                //create
                return View(new Departament());
            }
            else
            {
                //update
                Departament DepartamentObj = _unitOfWork.Departamentet.Get(u => u.Id == id);
                return View(DepartamentObj);
            }
        }
        [HttpPost]
        public IActionResult Upsert(Departament departamentetObj)
        {
            //if (obj.Lname == obj.Ldescription.ToString())
            //{
            //    ModelState.AddModelError("Emri", "Emri i lendes dhe pershkrimi nuk mund te jene te njejta");
            //}
            if (ModelState.IsValid)
            {
                if (departamentetObj.Id == 0)
                {
                    _unitOfWork.Departamentet.Add(departamentetObj);
                }
                else
                {
                    _unitOfWork.Departamentet.Update(departamentetObj);

                }
                _unitOfWork.Save();
                TempData["success"] = "Departamenti eshte krijuar me sukses";
                return RedirectToAction("Index");

            }
            else
            {
                return View(departamentetObj);
            }
            
        }
        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Departament> DepartamentetList = _unitOfWork.Departamentet.GetAll().ToList();
            return Json(new { data = DepartamentetList });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var departamentetToBeDeleted = _unitOfWork.Departamentet.Get(u => u.Id == id);
            if (departamentetToBeDeleted == null)
            {
                return Json(new
                {
                    success = false,
                    message = "error while deleting"
                });
            }
            _unitOfWork.Departamentet.Remove(departamentetToBeDeleted);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete successful" });
        }

        #endregion
    }
}

Consulting/Areas/Admin/Controllers/KonsultimetController.cs
using Consult.DataAcess.Data;
using Consult.Models;
using Consult.Models.ViewModels;
using Consult.Utility;
using Cunsult.DataAcess.Repository;
using Cunsult.DataAcess.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Data;
using System.Security.Claims;

namespace Consulting.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Profesor)]
    public class KonsultimetController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public KonsultimetController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<Konsultimet> KonsultimetList = _unitOfWork.Konsultimet.GetAll(includeProperties:"Lendet").ToList();
            return View(KonsultimetList);
        }
        
        public IActionResult Upsert(int? id)
        {
            KunsultimetVM KunsultimetVM = new()
            {
                LendList = _unitOfWork.Lendet
                .GetAll().Select(u => new SelectListItem
                    {
                         Text = u.Lname,
                         Value = u.Lid.ToString(),
                    }),
                Konsultimet = new Konsultimet()
            };
            if (id==null || id==0)
            {
                //create
                return View(KunsultimetVM);
            } else{
                //update
                KunsultimetVM.Konsultimet = _unitOfWork.Konsultimet.Get(u => u.Kid == id);
                return View(KunsultimetVM);
            }
        }
        [HttpPost]
        public IActionResult Upsert(KunsultimetVM konsultimetVM)
        {
            //if (obj.Lname == obj.Ldescription.ToString())
            //{
            //    ModelState.AddModelError("Emri", "Emri i lendes dhe pershkrimi nuk mund te jene te njejta");
            //}
            konsultimetVM.Konsultimet.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (ModelState.IsValid)
            {
                if(konsultimetVM.Konsultimet.Kid == 0)
                {
                    _unitOfWork.Konsultimet.Add(konsultimetVM.Konsultimet);
                }
                else
                {
                    _unitOfWork.Konsultimet.Update(konsultimetVM.Konsultimet);
                }
                TempData["success"] = "Konsultimi eshte krijuar me sukses";
                _unitOfWork.Save();
                return RedirectToAction("Index");

            }
            return View();
        }
        #region API Calls
        [HttpGet]
        public IActionResult GetAll() {
            List<Konsultimet> KonsultimetList = _unitOfWork.Konsultimet.GetAll(includeProperties: "Lendet").ToList();
            return Json(new {data =  KonsultimetList});
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var konsultimetToBeDeleted = _unitOfWork.Konsultimet.Get(u=> u.Kid == id);
            if(konsultimetToBeDeleted == null)
            {
                return Json(new
                {
                    success = false,
                    message = "error while deleting"
                });
            }
            _unitOfWork.Konsultimet.Remove(konsultimetToBeDeleted); 
            _unitOfWork.Save();
            return Json(new { success= true, message = "Delete successful"});
        }

        #endregion
    }
}

Consulting/Areas/Admin/Controllers/ProfesorController.cs
using Consult.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace Consulting.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class ProfesorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult _Form()
        {
            return PartialView();
        }
    }
}

Consulting/Controllers/LendetController.cs
using Consult.DataAcess.Data;
using Consult.Models;
using Cunsult.DataAcess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace Consult.Controllers
{
    public class LendetController : Controller
    {
        private readonly ILendetRepository _lendetrep;
        public LendetController(ILendetRepository db)
        {
            _lendetrep = db;
        }
        public IActionResult Index()
        {
            List<Lendet> LendetList = _lendetrep.GetAll().ToList();
            return View(LendetList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Lendet obj)
        {
            //if (obj.Lname == obj.Ldescription.ToString())
            //{
            //    ModelState.AddModelError("Emri", "Emri i lendes dhe pershkrimi nuk mund te jene te njejta");
            //}
            if (ModelState.IsValid)
            {
                _lendetrep.Add(obj);
                _lendetrep.Save();
                TempData["success"] = "Lenda eshte krijuar me sukses";
                return RedirectToAction("Index");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _lendetrep.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null) 
            {
                return NotFound(); 
            }
            return View(lendetprejdb);
        }
        [HttpPost]
        public IActionResult Edit(Lendet obj)
        {

            if (ModelState.IsValid)
            {
                _lendetrep.Update(obj);
                _lendetrep.Save();
                TempData["success"] = "Lenda eshte edituar me sukses";
                return RedirectToAction("Index");

            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Lendet? lendetprejdb = _lendetrep.Get(u => u.Lid == id);
            //Lendet? lendetprejdb1 = _db.Lendet.FirstOrDefault(u=>u.Lid==Lid);
            //Lendet? lendetprejdb2 = _db.Lendet.Where(u=>u.Lid == Lid).FirstOrDefault();
            if (lendetprejdb == null)
            {
                return NotFound();
            }
            return View(lendetprejdb);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Lendet? obj = _lendetrep.Get(u => u.Lid == id);
            if (obj == null)
            {
                return NotFound();
            }
            _lendetrep.Remove(obj);
            _lendetrep.Save();
            TempData["success"] = "Lenda eshte fshire me sukses";
            return RedirectToAction("Index");
        }
    }
}

Consulting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Consulting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Consulting.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Consulting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Student" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Student" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                         @if (User.IsInRole(SD.Role_Admin)) 
                         { 
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Menagment
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Lendet" asp-action="Index">Lendet</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Konsultimet" asp-action="Index">Konsultimet</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Departamentet" asp-action="Index">Dapartamentet</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Profesor" asp-action="Index">Profesorët</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                         } 
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            Made with <i class="bi bi-heart-fill"></i> from Consulting
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Consulting/Views/Shared/_Notification.cshtml
@if (TempData["success"] !=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}